Adding validation resource
giantswarm/app-operator pull request #472
Opened 2020-09-01 15:56 UTC by tomahawk28

## Checklist

- [ ] Update changelog in CHANGELOG.md.

2020-09-01 16:47 UTC, tomahawk28 commented
1. configmap not found
```
status:
  appVersion: ""
  release:
    lastDeployed: null
    reason: 'not found error: configmap `dd` in namespace `dd` not found'
    status: configmap-merge-failed
  version: ""
```
2. secret not found
```
status:
  appVersion: ""
  release:
    lastDeployed: null
    reason: 'not found error: secret `dd` in namespace `giantswarm` not found'
    status: secret-merge-failed
  version: ""
```

2020-09-02 11:46 UTC, tomahawk28 commented
When no namespace on the resource, 
```
status:
  appVersion: ""
  release:
    lastDeployed: null
    reason: namespace is not specified for secret `d`
    status: resource-not-found
```

2020-09-02 11:53 UTC, tomahawk28 commented
Changed as below format; 

```
status:
  appVersion: ""
  release:
    lastDeployed: null
    reason: secrets "x" not found
    status: resource-not-found
```

2020-09-02 13:57 UTC, tomahawk28 commented on service/controller/app/resource/status/create.go
> +		if cc.Status.ClusterStatus.IsUnavailable {
I moved these statements here since we need to update the app CR status even when the tenant cluster is not available.

2020-09-02 18:44 UTC, rossf7 requested changes
I really appreciate the efforts here and the desire to quickly improve the developer experience for customers. But this is going to need some rework and IMO we shouldn't be implementing validation logic like this without test coverage.

It would have been better to outline the design in https://github.com/giantswarm/giantswarm/issues/13045 once we decided to change it and add the new validation resource.

Soon we will want to create an app-admission-controller that also has this logic. So I think it would be better to put the validation logic in `pkg/validation` so it can be extracted later. Something like 

```go
func ValidateApp(ctx context.Context, cr *v1alpha1.App) (string, error) {
	...
	return reason, nil
}
```

I think the validation resource should execute first. If it doesn't pass then we set the CR status and cancel the reconciliation. Passing the status via the controller context is complex and is deprecated functionality in operatorkit.

For testing the ideal for me would be unit tests for `ValidateApp` with each case and the error we want to display to users. Plus a single step in the basic integration test to make sure the CR status is set OK. WDYT?

Also we'd talked about releasing this tomorrow for the Thursday deploys thing. But there is no rush here and this is my bad for not communicating that clearly.

IMO its much better to spend the time here to improve the design and make sure we have test coverage.

2020-09-03 10:23 UTC, tomahawk28 commented
> I think the validation resource should execute first. If it doesn't pass then we set the CR status and cancel the reconciliation. Passing the status via the controller context is complex and is deprecated functionality in operatorkit.

That's right, we are deprecating controller context so I think it makes sense that not to use that as you suggested. 

One thing I would like to point out, that `ValidateApp` spec may could be optimized as below, 

```golang
func ValidateApp(ctx context.Context, cr *v1alpha1.App) error {
	...
	return reason // or return nil
}
```

rather than using string as first parameter, we could utilize error variable returned by this function, WDYT?

2020-09-03 11:37 UTC, tomahawk28 commented
> Soon we will want to create an app-admission-controller that also has this logic. So I think it would be better to put the validation logic in pkg/validation so it can be extracted later.

Even if we put this function in `resource.go` in `validation`, extraction would work as same. So why not in the `resource.go` file?

2020-09-03 18:44 UTC, tomahawk28 commented
tested in `ghost`
Logs:
```
W 09/03 18:15:45 /apis/application.giantswarm.io/v1alpha1/namespaces/giantswarm/apps/chart-operator-unique validation validation error validation error: configmap `d` in namespace `dd` not found | app-operator/v2/service/controller/app/resource/validation/create.go:24 | controller=app-operator | event=update | loop=279 | version=128656135
```

yaml:

```
status:
  appVersion: ""
  release:
    lastDeployed: null
    reason: 'validation error: configmap `d` in namespace `dd` not found'
    status: resource-not-found
  version: ""
```

2020-09-04 09:46 UTC, rossf7 approved these changes
LGTM ❤️ 

@tomahawk28 Thanks this works great and will improve the developer experience. As well as hopefully reducing support requests.🤞

2020-09-04 09:59 UTC, merged