change kubeconfig secret key from kubeConfig to values
giantswarm/app-operator pull request #715
Opened 2021-03-11 16:23 UTC by TheoBrigitte

Towards: https://github.com/giantswarm/giantswarm/issues/16005

Uses https://github.com/giantswarm/kubeconfig/pull/60 so we can fetch kubeconfig from CAPI.

2021-03-12 09:50 UTC, tomahawk28 requested changes

2021-03-12 09:50 UTC, tomahawk28 commented on service/watcher/chartstatus/g8sclient.go
> +		restConfig, err = kubeConfig.NewRESTConfigForApp(ctx, kubeConfigName, c.appNamespace, "values")
We have kubeconfig secrets which have a key `kubeConfig`, so I think we need a fallback mechanism. (this is why we are failing in the integration-test)
1. check `kubeConfig` key first 
2. if not, check `values` key

2021-03-12 09:51 UTC, tomahawk28 commented on service/controller/app/resource/clients/resource.go
> +		restConfig, err = kubeConfig.NewRESTConfigForApp(ctx, key.KubeConfigSecretName(cr), key.KubeConfigSecretNamespace(cr), "values")
Here also we need to update.

2021-03-19 12:00 UTC, rossf7 commented
@TheoBrigitte Going to close this as it was done in 4.1.0. Hope thats OK. 🙏

2021-03-19 12:00 UTC, closed without merging